export default {
  REQUEST_LOAD_PROFILE: 'REQUEST_LOAD_PROFILE',
  RECEIVE_LOAD_PROFILE: 'RECEIVE_LOAD_BADGES',
  RECEIVE_LOAD_PROFILE_ERROR: 'RECEIVE_LOAD_PROFILE_ERROR',
  REQUEST_SAVE_PROFILE: 'REQUEST_SAVE_PROFILE',
  RECEIVE_SAVE_PROFILE: 'RECEIVE_SAVE_PROFILE',
  RECEIVE_SAVE_PROFILE_ERROR: 'RECEIVE_SAVE_PROFILE_ERROR',
};
