export default {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_SIGNUP: 'AUTH_SIGNUP',
  RECEIVE_AUTH_SUCCESS: 'RECEIVE_AUTH_SUCCESS',
  RECEIVE_AUTH_ERROR: 'RECEIVE_AUTH_ERROR',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_PASSWORD_RESET: 'AUTH_PASSWORD_RESET',
  AUTH_NEW_PASSWORD: 'AUTH_NEW_PASSWORD',
  SET_REQUEST_HEADER: 'SET_REQUEST_HEADER',
  RESET_REQUEST_HEADER: 'RESET_REQUEST_HEADER',
};
